name: godal

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  testGeneral:
    name: General test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: |
        go test -cover -coverprofile=coverage_general.txt -v .
        bash <(curl -s https://codecov.io/bash) -cF general
